In [1]:
import numpy as np

In [6]:
import numpy as np
arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)
# no () in ndim, shape, size,dtype

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [9]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a*b
c#works fine

array([ 4, 10, 18])

In [11]:
b=np.array([[1,2,3],[1.1,2.3,4.5]])
b

array([[1. , 2. , 3. ],
       [1.1, 2.3, 4.5]])

In [13]:
b.ndim

2

In [14]:
b.shape

(2, 3)

In [15]:
b.size

6

In [16]:
type(b)

numpy.ndarray

In [17]:
b.dtype

dtype('float64')

In [18]:
# change dtype
a=np.array([1,2,3,4],dtype=np.int64)

In [19]:
a.dtype

dtype('int64')

In [20]:
# change dtype
x=np.array([1,2,3,4],dtype='int8') 

In [22]:
x.dtype

dtype('int8')

In [24]:
x.itemsize#number of bytes of each item

1

In [25]:
a.itemsize 

8

In [28]:
# total bytes = nbytes = itemsize*size
print(a.size)
print(a.itemsize)
print(a.nbytes)
print(a.size*a.itemsize)

4
8
32
32


In [2]:
a=[1,2,3,4,5,6,7,8,9,10,11]
ar=np.array(a)

In [3]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
ar+10   #WORKS (not mutuates array)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [5]:
ar*2    
# (not mutuates array)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [6]:
sum(a)

66

In [7]:
a=np.array([[1,2],[3,4]])

In [8]:
b=np.array([[1,2,3],[4,5,6]])

In [9]:
a

array([[1, 2],
       [3, 4]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b=b.T.shape

In [18]:
print(a*b) #element wise multiplication

[[3 4]
 [9 8]]


In [22]:
x=np.array([1,4,9,14])
np.sqrt(x) #WORKS

array([1.        , 2.        , 3.        , 3.74165739])

In [23]:
# .T is transpose

In [24]:
a=np.arange(4,20,5)

In [25]:
a

array([ 4,  9, 14, 19])

In [28]:
a.reshape(4,1)

array([[ 4],
       [ 9],
       [14],
       [19]])

In [29]:
# in arange we can use floats but not in range 

In [31]:
va = np.array([[1, 4], [5, 6]])
vb = np.array([[2, 4], [5, 2]])


In [33]:
va

array([[1, 4],
       [5, 6]])

In [34]:
vb

array([[2, 4],
       [5, 2]])

In [38]:
# matrix multiplication
np.dot(va,vb)

array([[22, 12],
       [40, 32]])

In [39]:
np.vdot(va,vb) #1*2+4*4+5*5+6*2 = 55

55

In [41]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.full((2,5),1.2) #np.full((shape),value)

array([[1.2, 1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2, 1.2]])

In [44]:
arr=np.array([1,23,4,4,45,8,91,71])

In [45]:
arr[arr>30]

array([45, 91, 71])

In [46]:
arr>30

array([False, False, False, False,  True, False,  True,  True])

In [47]:
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])

In [48]:
arr

array([[1, 5, 6],
       [4, 7, 2],
       [3, 1, 9]])

In [49]:
arr.sum()

38

In [51]:
arr.cumsum()

array([ 1,  6, 12, 16, 23, 25, 28, 29, 38])

In [52]:
arr.cumsum(1)

array([[ 1,  6, 12],
       [ 4, 11, 13],
       [ 3,  4, 13]])

In [54]:
arr.cumsum(axis=1)

array([[ 1,  6, 12],
       [ 4, 11, 13],
       [ 3,  4, 13]])